# Generated by Django 5.1.2 on 2024-11-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication', models.CharField(max_length=50)),
                ('Dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=35)),
                ('additional_notes', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=25)),
                ('Date', models.DateField(max_length=8)),
                ('time', models.TimeField(max_length=8)),
                ('reason', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
