# Generated by Django 5.1.2 on 2024-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_medicine_delete_medicines_remove_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='register',
            name='time',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Dosage',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Medication',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
