# Generated by Django 5.1.2 on 2024-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_appointment_remove_register_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Medication',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
