# Generated by Django 5.1.2 on 2024-11-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_register_email_alter_medicine_medication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
