# Generated by Django 5.1.2 on 2024-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Medication',
            field=models.CharField(max_length=100),
        ),
    ]
