# Generated by Django 5.1.2 on 2024-11-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_medicine_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='mail',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
