# Generated by Django 5.1.2 on 2024-11-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_register_mail_alter_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
