# Generated by Django 5.1.2 on 2024-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_register_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Reason',
            field=models.TextField(blank=True, default='Sick', max_length=80),
        ),
    ]
