# Generated by Django 5.1.2 on 2024-12-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_appointment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mail',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
